//API_1
GET http://localhost:3000/states/
###

//API_2
GET http://localhost:3000/states/1
###

//API_3
POST http://localhost:3000/districts/

Content-Type : application/json
{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

//API_4
GET http://localhost:3000/districts/12


###

//API_5

DELETE http://localhost:3000/districts/322/
###

//API_6
PUT http://localhost:3000/districts/32/

Content-Type : application/json
{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

//API_7
GET http://localhost:3000/states/12/stats/

###

//API_8
GET http://localhost:3000/districts/12/details/




